# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "drupal"
  config.vm.customize([
      "modifyvm", :id,
      "--name", "DrupalStack",
      "--memory", "1024"
  ])
  
  config.vm.forward_port 80, 8080
  config.vm.network :bridged
  config.vm.network :hostonly, "10.11.12.13"
  config.vm.share_folder "v-data", "/home/vagrant/project", "./project"

  # config.vm.provision :puppet do |puppet|
  #    puppet.manifests_path = "./puppet/manifests"
  #    puppet.module_path = "./puppet/modules"
  #    puppet.manifest_file = "init.pp"
  # end

end
